name: Detect High-Impact Function Changes

on:
  pull_request:
    paths:
      - "**.js"
      - "**.ts"

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run impact detector
        run: node scripts/run.js
